name: labelme
on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:
jobs:
  user-and-time:
    runs-on: ubuntu-latest
    name: Running a simple BASH script
    steps:
      - name: A simple BASH script
        id: BASH
        uses: johndohoneyjr/a-docker-action@main
